### ISSUE TITLE
Dimension Mismatch error after changing Architecture

### ISSUE THREAD

**Issue by Durgesh92** [YiwenShaoStephen/pychain_example#4]
I have tried changing architecture to LSTM and RNN but getting this dimension mismatch error. 

RuntimeError: Gather got an input of invalid size: got [32, 11, 86], but expected [32, 12, 86]

Also, I can't enable drop_last=True option in AudioDataLoader because it already uses batch_sampler option.

**Comment by busishengui** [comment]
@Durgesh92 


As for RNN, I have tried it. This problem is because different batches are allocated to different GPUs during RNN training. You need to unify the length in the batch in the RNN model code.
