### ISSUE TITLE
Loss nan

### ISSUE THREAD

**Issue by cocoakeith** [YiwenShaoStephen/pychain_example#6]
I have tried to use my own 8k data with mini_librispeech script but getting the nan loss. Here is the detail
![image](https://user-images.githubusercontent.com/12630218/92575219-a556f600-f2ba-11ea-84e0-700b69072bde.png)

**Comment by xin-w8023** [comment]
Hi, when I run the train.py on gpu, it crashed. did you ever get the same problem? More detail in #7

**Comment by sailordiary** [comment]
In my case this was due to some samples having too few #frames (similar to the case in CTC where input_length < target_length). I removed such samples and the model trains normally without NaNs.
